/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzworks;


/**
 *
 * @author Simon Junga (simonthechipmunk)
 */
public class GameWindowPanelReverseMusic extends javax.swing.JPanel {

    /**
     * Creates new form GameWindowPanelReverseMusic
     */
    public GameWindowPanelReverseMusic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_Artist = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        jLabel_Image.setBackground(java.awt.Color.white);
        jLabel_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/reverse_music.png"))); // NOI18N
        jLabel_Image.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel_Title.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(28, 74, 120));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("Title");
        jLabel_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_Artist.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        jLabel_Artist.setForeground(new java.awt.Color(28, 74, 120));
        jLabel_Artist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Artist.setText("Artist");
        jLabel_Artist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
            .addComponent(jLabel_Artist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Artist, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 476, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTitleArtist(String title, String artist){
        jLabel_Title.setText(title);
        jLabel_Artist.setText(artist);
    }
    
    public void setReset(){
        jLabel_Title.setText(" ");
        jLabel_Artist.setText("?");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Artist;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Title;
    // End of variables declaration//GEN-END:variables
}
