/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzworks;

import javax.swing.Icon;

/**
 *
 * @author Simon Junga (simonthechipmunk)
 */
public class GameWindowPanelWhoIsIt extends javax.swing.JPanel {

    /**
     * Creates new form GameWindowPanelReverseMusic
     */
    public GameWindowPanelWhoIsIt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Name = new javax.swing.JLabel();
        jLabel_Image = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        jLabel_Name.setFont(new java.awt.Font("Cantarell", 0, 60)); // NOI18N
        jLabel_Name.setForeground(new java.awt.Color(28, 74, 120));
        jLabel_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Name.setText("Name");
        jLabel_Name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_Image.setBackground(java.awt.Color.white);
        jLabel_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/who_is_it.png"))); // NOI18N
        jLabel_Image.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
            .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setName(String name){
        jLabel_Name.setText(name);
    }
    
    public void setImage(Icon icon){
        jLabel_Image.setIcon(icon);
    }
    
    public void setReset(){
        jLabel_Name.setText("?");
        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/who_is_it.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Name;
    // End of variables declaration//GEN-END:variables
}
