/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzworks;

import java.awt.Toolkit;
import java.io.OutputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Simon Junga (simonthechipmunk)
 */
public class mainWindow extends javax.swing.JFrame {
    
    private Serial serial;
    private BuzzWatch buzzwatch;
    private ArrayList<Integer> teamlist;
    private ArrayList<TeamPanel> teampanels;

    /**
     * Creates new form mainWindow
     */
    public mainWindow(Serial serial, ArrayList<Integer> teamlist) {
        this.teampanels = new ArrayList();
        this.serial = serial;
        this.teamlist = teamlist;
        
        //start serial buzz watcher
        buzzwatch = new BuzzWatch(this);
        new Thread(buzzwatch).start();
        
        initComponents();
        jLabel_TeamBuzzed.setVisible(false);
        
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/home/simon/.NetBeansProjects/BuzzWorks/Icons/icon.png")));

        this.setTitle("Buzzworks - Controls");
        
        for (int i = 0; i < teamlist.size(); i++) {
            teampanels.add(new TeamPanel(teamlist.get(i).intValue(), this.serial, this.jTabbedPane4));
            jTabbedPane4.addTab(teampanels.get(i).team.getName(), teampanels.get(i));
        }
        
        //reset buzzers
        serial.Send("all:mode.0\n");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        teamPanelAll1 = new buzzworks.TeamPanelAll(serial, teampanels);
        jPanel3 = new javax.swing.JPanel();
        jButton_ResetAll = new javax.swing.JButton();
        jLabel_TeamBuzzed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jTabbedPane4.addTab("All Teams", teamPanelAll1);

        jButton_ResetAll.setText("Reset Buzzers");
        jButton_ResetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetAllActionPerformed(evt);
            }
        });

        jLabel_TeamBuzzed.setFont(new java.awt.Font("Cantarell", 0, 80)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_TeamBuzzed, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_ResetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_ResetAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel_TeamBuzzed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ResetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetAllActionPerformed
        // TODO add your handling code here:
        serial.Send("all:buzz.reset\n");
        
        //reset global tag
        jLabel_TeamBuzzed.setVisible(false);
    }//GEN-LAST:event_jButton_ResetAllActionPerformed
    
    private void buzzhandler(String address) {

        //activate teamtab
        for (int e = 0; e < teampanels.size(); e++) {
            
            if (teampanels.get(e).team.getAddress() == Integer.parseInt(address)) {
                for (int i = 0; i < jTabbedPane4.getTabCount(); i++) {
                    if (jTabbedPane4.getTitleAt(i).equals(teampanels.get(e).team.getName())) {
                        jTabbedPane4.setSelectedIndex(i);
                        
                        //set global tag
                        jLabel_TeamBuzzed.setText("→ " + teampanels.get(e).team.getName());
                        jLabel_TeamBuzzed.setForeground(teampanels.get(e).team.getColor());
                        jLabel_TeamBuzzed.setVisible(true);
                        break;
                    }
                }
                break;
            }
        }
    }
    
    private class BuzzWatch implements Runnable {
        
        mainWindow parent;
        
        public BuzzWatch(mainWindow parent) {
            this.parent = parent;
        }
        
        @Override
        public void run() {
            //background

            Scanner scanner = new Scanner(serial.in);
            try {
                
                while (true) {
                    //scan                    
                    String inStr = scanner.nextLine();
                    
                    if (inStr.indexOf(':') != -1) {
                        if (inStr.substring(inStr.indexOf(':') + 1).equals("is.buzzed")) {
                            parent.buzzhandler(inStr.substring(0, inStr.indexOf(':')));
                        }
                    }
                }
                
            } catch (Exception e) {
                
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ResetAll;
    private javax.swing.JLabel jLabel_TeamBuzzed;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private buzzworks.TeamPanelAll teamPanelAll1;
    // End of variables declaration//GEN-END:variables
}
