/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzworks;

import java.util.ArrayList;

/**
 *
 * @author Simon Junga (simonthechipmunk)
 */
public class TeamPanelAll extends javax.swing.JPanel {

    private Serial serial;
    private ArrayList<TeamPanel> teampanels;
    
    /**
     * Creates new form TeamPanel
     */
    public TeamPanelAll() {
        //init teampanel
        initComponents();        
    }

    /**
     * Creates new form TeamPanel
     * @param address the Buzzer Address
     * @param 
     */
    public TeamPanelAll(Serial serial, ArrayList teampanels) {
        this.serial = serial;
        this.teampanels = teampanels;
        
        //init teampanel
        initComponents();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_TeamMode = new javax.swing.JComboBox<>();
        jButton_AllDeactivate = new javax.swing.JButton();
        jButton_AllActivate = new javax.swing.JButton();
        jButton_AllUnlock = new javax.swing.JButton();
        jButton_AllLock = new javax.swing.JButton();
        jColorChooser_AllColor = new javax.swing.JColorChooser();
        jButton_AllSetIdleCol = new javax.swing.JButton();
        jButton_AllSetLockCol = new javax.swing.JButton();
        jButton_AllSetActiveCol = new javax.swing.JButton();
        jLabel_Header = new javax.swing.JLabel();

        jComboBox_TeamMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mode 0 (Test)", "Mode 1", "Mode 2", "Mode 3", "Mode 4", "Mode 5" }));
        jComboBox_TeamMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TeamModeActionPerformed(evt);
            }
        });

        jButton_AllDeactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/window-close-symbolic.symbolic.png"))); // NOI18N
        jButton_AllDeactivate.setText("Deactivate All");
        jButton_AllDeactivate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AllDeactivate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AllDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllDeactivateActionPerformed(evt);
            }
        });

        jButton_AllActivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/emblem-ok-symbolic.symbolic.png"))); // NOI18N
        jButton_AllActivate.setText("Activate All");
        jButton_AllActivate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AllActivate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AllActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllActivateActionPerformed(evt);
            }
        });

        jButton_AllUnlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/rotation-locked-symbolic.png"))); // NOI18N
        jButton_AllUnlock.setText("Unlock All");
        jButton_AllUnlock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AllUnlock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AllUnlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllUnlockActionPerformed(evt);
            }
        });

        jButton_AllLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/system-lock-screen-symbolic.symbolic.png"))); // NOI18N
        jButton_AllLock.setText("Lock All");
        jButton_AllLock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AllLock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AllLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllLockActionPerformed(evt);
            }
        });

        jButton_AllSetIdleCol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/preferences-color-symbolic.symbolic.png"))); // NOI18N
        jButton_AllSetIdleCol.setText("Set Idle Color");
        jButton_AllSetIdleCol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AllSetIdleCol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AllSetIdleCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllSetIdleColActionPerformed(evt);
            }
        });

        jButton_AllSetLockCol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/preferences-color-symbolic.symbolic.png"))); // NOI18N
        jButton_AllSetLockCol.setText("Set Lock Color");
        jButton_AllSetLockCol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AllSetLockCol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AllSetLockCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllSetLockColActionPerformed(evt);
            }
        });

        jButton_AllSetActiveCol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/preferences-color-symbolic.symbolic.png"))); // NOI18N
        jButton_AllSetActiveCol.setText("Set Active Color");
        jButton_AllSetActiveCol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AllSetActiveCol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AllSetActiveCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllSetActiveColActionPerformed(evt);
            }
        });

        jLabel_Header.setFont(new java.awt.Font("Cantarell", 0, 60)); // NOI18N
        jLabel_Header.setText("Team Independent Settings");
        jLabel_Header.setMaximumSize(new java.awt.Dimension(323, 76));
        jLabel_Header.setMinimumSize(new java.awt.Dimension(323, 76));
        jLabel_Header.setPreferredSize(new java.awt.Dimension(323, 76));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_AllSetIdleCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_AllSetLockCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_AllSetActiveCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jColorChooser_AllColor, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_AllLock, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_AllUnlock, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_AllActivate, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_AllDeactivate, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGap(69, 69, 69)
                        .addComponent(jComboBox_TeamMode, 0, 223, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_AllDeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_TeamMode, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AllActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AllUnlock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AllLock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jColorChooser_AllColor, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_AllSetIdleCol, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_AllSetLockCol, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_AllSetActiveCol, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_TeamModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TeamModeActionPerformed
        // TODO add your handling code here:
        serial.Send("all:mode." + jComboBox_TeamMode.getSelectedIndex() + "\n");
        
        for(int i=0; i<teampanels.size(); i++){
            teampanels.get(i).team.setMode(jComboBox_TeamMode.getSelectedIndex());
            teampanels.get(i).setTeamModeCombobox(jComboBox_TeamMode.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBox_TeamModeActionPerformed

    private void jButton_AllActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllActivateActionPerformed
        // TODO add your handling code here:
        serial.Send("all:active.1\n");
    }//GEN-LAST:event_jButton_AllActivateActionPerformed

    private void jButton_AllUnlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllUnlockActionPerformed
        // TODO add your handling code here:
        serial.Send("all:lock.0\n");

    }//GEN-LAST:event_jButton_AllUnlockActionPerformed

    private void jButton_AllLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllLockActionPerformed
        // TODO add your handling code here:
        serial.Send("all:lock.1\n"); 
    }//GEN-LAST:event_jButton_AllLockActionPerformed

    private void jButton_AllDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllDeactivateActionPerformed
        // TODO add your handling code here:
        serial.Send("all:active.0\n");
    }//GEN-LAST:event_jButton_AllDeactivateActionPerformed

    private void jButton_AllSetIdleColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllSetIdleColActionPerformed
        // TODO add your handling code here:
        serial.Send("all:icolor." + jColorChooser_AllColor.getColor().getRGB() + "\n");
    }//GEN-LAST:event_jButton_AllSetIdleColActionPerformed

    private void jButton_AllSetLockColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllSetLockColActionPerformed
        // TODO add your handling code here:
        serial.Send("all:lcolor." + jColorChooser_AllColor.getColor().getRGB() + "\n");
    }//GEN-LAST:event_jButton_AllSetLockColActionPerformed

    private void jButton_AllSetActiveColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllSetActiveColActionPerformed
        // TODO add your handling code here:
        serial.Send("all:acolor." + jColorChooser_AllColor.getColor().getRGB() + "\n");
    }//GEN-LAST:event_jButton_AllSetActiveColActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AllActivate;
    private javax.swing.JButton jButton_AllDeactivate;
    private javax.swing.JButton jButton_AllLock;
    private javax.swing.JButton jButton_AllSetActiveCol;
    private javax.swing.JButton jButton_AllSetIdleCol;
    private javax.swing.JButton jButton_AllSetLockCol;
    private javax.swing.JButton jButton_AllUnlock;
    private javax.swing.JColorChooser jColorChooser_AllColor;
    private javax.swing.JComboBox<String> jComboBox_TeamMode;
    private javax.swing.JLabel jLabel_Header;
    // End of variables declaration//GEN-END:variables
}
