/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzworks;

import java.awt.Color;
import java.util.Random;
import javax.swing.JTabbedPane;

/**
 *
 * @author Simon Junga (simonthechipmunk)
 */
public class TeamPanel extends javax.swing.JPanel {

    public Team team;
    private Serial serial;
    private JTabbedPane tabpane;
    
    /**
     * Creates new form TeamPanel
     */
    public TeamPanel() {
        team = new Team();
        
        //init teampanel
        initComponents();        
    }

    /**
     * Creates new form TeamPanel
     * @param address the Buzzer Address
     * @param 
     */
    public TeamPanel(int address, Serial serial, JTabbedPane tabpane) {
        team = new Team();
        this.serial = serial;
        this.tabpane = tabpane;
        team.setAddress(address);
        
        //init teampanel
        initComponents();
        jList_TeamPoints.setSelectedIndex(0);
        
        //set initial color
        Random rand = new Random();
        Color col = new Color(rand.nextInt(255)+1, rand.nextInt(255)+1, rand.nextInt(255)+1);
        setTeamColor(col);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TeamName = new javax.swing.JLabel();
        jLabel_TeamAddress = new javax.swing.JLabel();
        jTextField_TeamName = new javax.swing.JTextField();
        jComboBox_TeamMode = new javax.swing.JComboBox<>();
        jButton_TeamDeactivate = new javax.swing.JButton();
        jButton_TeamActivate = new javax.swing.JButton();
        jButton_TeamUnlock = new javax.swing.JButton();
        jButton_TeamLock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_TeamPoints = new javax.swing.JList<>();
        jButton_TeamAddPoints = new javax.swing.JButton();
        jButton_TeamTakePoints = new javax.swing.JButton();
        jLabel_TeamPoints = new javax.swing.JLabel();
        jColorChooser_TeamColor = new javax.swing.JColorChooser();
        jButton_TeamApplyName = new javax.swing.JButton();

        jLabel_TeamName.setFont(new java.awt.Font("Cantarell", 0, 80)); // NOI18N
        jLabel_TeamName.setText(team.getName());

        jLabel_TeamAddress.setFont(new java.awt.Font("Cantarell", 0, 150)); // NOI18N
        jLabel_TeamAddress.setText(new Integer(team.getAddress()).toString());

        jTextField_TeamName.setText(team.getName());

        jComboBox_TeamMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mode 0 (Test)", "Mode 1", "Mode 2", "Mode 3", "Mode 4", "Mode 5" }));
        jComboBox_TeamMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TeamModeActionPerformed(evt);
            }
        });

        jButton_TeamDeactivate.setText("Deactivate");
        jButton_TeamDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TeamDeactivateActionPerformed(evt);
            }
        });

        jButton_TeamActivate.setText("Activate");
        jButton_TeamActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TeamActivateActionPerformed(evt);
            }
        });

        jButton_TeamUnlock.setText("Unlock");
        jButton_TeamUnlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TeamUnlockActionPerformed(evt);
            }
        });

        jButton_TeamLock.setText("Lock");
        jButton_TeamLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TeamLockActionPerformed(evt);
            }
        });

        jList_TeamPoints.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "5", "10", "20", "50", "100", "300" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_TeamPoints.setMinimumSize(new java.awt.Dimension(200, 259));
        jList_TeamPoints.setPreferredSize(new java.awt.Dimension(200, 259));
        jScrollPane1.setViewportView(jList_TeamPoints);

        jButton_TeamAddPoints.setText("Add");
        jButton_TeamAddPoints.setMinimumSize(new java.awt.Dimension(60, 37));
        jButton_TeamAddPoints.setPreferredSize(new java.awt.Dimension(60, 37));
        jButton_TeamAddPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TeamAddPointsActionPerformed(evt);
            }
        });

        jButton_TeamTakePoints.setText("Take");
        jButton_TeamTakePoints.setMinimumSize(new java.awt.Dimension(60, 37));
        jButton_TeamTakePoints.setPreferredSize(new java.awt.Dimension(60, 37));
        jButton_TeamTakePoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TeamTakePointsActionPerformed(evt);
            }
        });

        jLabel_TeamPoints.setFont(new java.awt.Font("Cantarell", 1, 60)); // NOI18N
        jLabel_TeamPoints.setText("0");

        jButton_TeamApplyName.setText("Apply Name");
        jButton_TeamApplyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TeamApplyNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_TeamName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_TeamAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_TeamAddPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_TeamTakePoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel_TeamPoints, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jColorChooser_TeamColor, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton_TeamLock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_TeamUnlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_TeamActivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_TeamDeactivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_TeamMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_TeamName)
                                    .addComponent(jButton_TeamApplyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_TeamAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TeamName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_TeamName, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_TeamApplyName))
                    .addComponent(jButton_TeamDeactivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_TeamActivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_TeamUnlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_TeamLock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_TeamMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_TeamAddPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton_TeamTakePoints, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_TeamPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jColorChooser_TeamColor, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jColorChooser_TeamColor.getSelectionModel().addChangeListener(new javax.swing.event.ChangeListener() {
            @Override
            public void stateChanged(javax.swing.event.ChangeEvent arg0) {
                setTeamColor(jColorChooser_TeamColor.getColor());
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_TeamModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TeamModeActionPerformed
        // TODO add your handling code here:
        team.setMode(jComboBox_TeamMode.getSelectedIndex());
        serial.Send(team.getAddress() + ":mode." + jComboBox_TeamMode.getSelectedIndex() + "\n");
    }//GEN-LAST:event_jComboBox_TeamModeActionPerformed

    private void jButton_TeamDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TeamDeactivateActionPerformed
        // TODO add your handling code here:      
        serial.Send(team.getAddress() + ":active.0\n");
    }//GEN-LAST:event_jButton_TeamDeactivateActionPerformed

    private void jButton_TeamActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TeamActivateActionPerformed
        // TODO add your handling code here:
        serial.Send(team.getAddress() + ":active.1\n");
    }//GEN-LAST:event_jButton_TeamActivateActionPerformed

    private void jButton_TeamUnlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TeamUnlockActionPerformed
        // TODO add your handling code here:
        serial.Send(team.getAddress() + ":lock.0\n");

    }//GEN-LAST:event_jButton_TeamUnlockActionPerformed

    private void jButton_TeamLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TeamLockActionPerformed
        // TODO add your handling code here:
        serial.Send(team.getAddress() + ":lock.1\n"); 
    }//GEN-LAST:event_jButton_TeamLockActionPerformed

    private void jButton_TeamAddPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TeamAddPointsActionPerformed
        // TODO add your handling code here:
        try{
            int points = Integer.parseInt(jList_TeamPoints.getSelectedValue());
            team.addPoints(points);
            jLabel_TeamPoints.setText(new Integer(team.getPoints()).toString());
        }
        catch(NumberFormatException e){
            
        }
    }//GEN-LAST:event_jButton_TeamAddPointsActionPerformed

    private void jButton_TeamTakePointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TeamTakePointsActionPerformed
        // TODO add your handling code here:
        try{
            int points = Integer.parseInt(jList_TeamPoints.getSelectedValue());
            team.subPoints(points);
            jLabel_TeamPoints.setText(new Integer(team.getPoints()).toString());
        }
        catch(NumberFormatException e){
            
        }
    }//GEN-LAST:event_jButton_TeamTakePointsActionPerformed

    private void jButton_TeamApplyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TeamApplyNameActionPerformed
        // TODO add your handling code here:
        try{
            String name = jTextField_TeamName.getText();
            
            for(int i = 0; i<tabpane.getTabCount(); i++){
                if(tabpane.getTitleAt(i).equals(team.getName())){
                    tabpane.setTitleAt(i, name);
                }
            }
          
            jLabel_TeamName.setText(name);
            team.setName(name);
        }
        catch(NullPointerException e){
            
        }
                            
    }//GEN-LAST:event_jButton_TeamApplyNameActionPerformed

    private void setTeamColor(Color color){
        
        //set colors
        serial.Send(team.getAddress() + ":tcolor." + color.getRGB() + "\n");
        jLabel_TeamName.setForeground(color);
        team.setColor(color);

        //set tabcolor
        for(int i = 0; i<tabpane.getTabCount(); i++){
            if(tabpane.getTitleAt(i).equals(team.getName())){
                tabpane.setForegroundAt(i, color);
                break;
            }
        }
    }
    
    public void setTeamModeCombobox(int index){
        jComboBox_TeamMode.setSelectedIndex(index);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_TeamActivate;
    private javax.swing.JButton jButton_TeamAddPoints;
    private javax.swing.JButton jButton_TeamApplyName;
    private javax.swing.JButton jButton_TeamDeactivate;
    private javax.swing.JButton jButton_TeamLock;
    private javax.swing.JButton jButton_TeamTakePoints;
    private javax.swing.JButton jButton_TeamUnlock;
    private javax.swing.JColorChooser jColorChooser_TeamColor;
    private javax.swing.JComboBox<String> jComboBox_TeamMode;
    private javax.swing.JLabel jLabel_TeamAddress;
    private javax.swing.JLabel jLabel_TeamName;
    private javax.swing.JLabel jLabel_TeamPoints;
    private javax.swing.JList<String> jList_TeamPoints;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_TeamName;
    // End of variables declaration//GEN-END:variables
}
