/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzworks;

import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Simon Junga (simonthechipmunk)
 */
public class TeamPanelPoints extends javax.swing.JPanel {

    private ArrayList<TeamPanel> teampanels;
    
    /**
     * Creates new form TeamPanelPoints
     */
    public TeamPanelPoints() {
        initComponents();
    }
    /**
     * Creates new form TeamPanelPoints
     */
    public TeamPanelPoints(ArrayList<TeamPanel> teampanels) {
        this.teampanels = teampanels;
        initComponents();
        
        //set jLabel renderer for list
        jList_Teams.setCellRenderer(new LabelRenderer());
        jList_Points.setCellRenderer(new LabelRenderer());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Teams = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Points = new javax.swing.JList<>();
        jLabel_Header = new javax.swing.JLabel();

        jList_Teams.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        jList_Teams.setMinimumSize(new java.awt.Dimension(400, 0));
        jScrollPane1.setViewportView(jList_Teams);

        jList_Points.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        jList_Points.setMaximumSize(new java.awt.Dimension(300, 0));
        jList_Points.setMinimumSize(new java.awt.Dimension(200, 0));
        jList_Points.setPreferredSize(new java.awt.Dimension(200, 0));
        jScrollPane3.setViewportView(jList_Points);

        jLabel_Header.setFont(new java.awt.Font("Cantarell", 0, 60)); // NOI18N
        jLabel_Header.setText("Team Points");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //update the teamlist
    public void updateList(){
        
        DefaultListModel model_teams = new DefaultListModel();
        DefaultListModel model_points = new DefaultListModel();
        
        for(int i=0; i<teampanels.size(); i++){
            JLabel label = new JLabel(teampanels.get(i).team.getName());
            label.setForeground(teampanels.get(i).team.getColor());
            label.setFont(new Font(label.getFont().getName(), Font.PLAIN, 60));
            model_teams.addElement(label);
            
            label = new JLabel(Integer.toString(teampanels.get(i).team.getPoints()));
            label.setForeground(teampanels.get(i).team.getColor());
            label.setFont(new Font(label.getFont().getName(), Font.PLAIN, 60));
            model_points.addElement(label);
        }
        
        jList_Teams.setModel(model_teams);
        jList_Points.setModel(model_points);
    }

    //listrenderer used to display jLabel components in the list
    private class LabelRenderer implements ListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            JLabel renderer = (JLabel) value;
            //renderer.setBackground(isSelected ? Color.red : list.getBackground());
            return renderer;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Header;
    private javax.swing.JList<String> jList_Points;
    private javax.swing.JList<String> jList_Teams;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
