/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzworks;

import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Simon Junga (simonthechipmunk)
 */
public class TeamWindowPoints extends javax.swing.JFrame {

    private ArrayList<TeamPanel> teampanels;
    
    private int buzzed_address = -1;
    
    /**
     * Creates new form TeamWindowPoints
     */
    public TeamWindowPoints() {
        initComponents();
    }

    public TeamWindowPoints(ArrayList teampanels){
        this.teampanels = teampanels;
        
        //set window title
        this.setTitle("Buzzworks - TeamChart");
        
        //init window components
        initComponents();
        //jList_Teams.setEnabled(false);
        //jList_Points.setEnabled(false);
        
        //set jLabel renderer for list
        jList_Teams.setCellRenderer(new TeamWindowPoints.LabelRenderer());
        jList_Points.setCellRenderer(new TeamWindowPoints.LabelRenderer());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Teams = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Points = new javax.swing.JList<>();

        jList_Teams.setMinimumSize(new java.awt.Dimension(350, 0));
        jList_Teams.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jList_Teams);

        jList_Points.setMinimumSize(new java.awt.Dimension(200, 0));
        jScrollPane2.setViewportView(jList_Points);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //update the teamlist
    public void updateList(){
        
        DefaultListModel model_teams = new DefaultListModel();
        DefaultListModel model_points = new DefaultListModel();
        
        int selected_index = -1;

        for(int i=0; i<teampanels.size(); i++){
            JLabel label = new JLabel(teampanels.get(i).team.getName());
            label.setForeground(teampanels.get(i).team.getColor());
            label.setFont(new Font(label.getFont().getName(), Font.PLAIN, 90));
            model_teams.addElement(label);
            
            label = new JLabel(Integer.toString(teampanels.get(i).team.getPoints()));
            label.setForeground(teampanels.get(i).team.getColor());
            label.setFont(new Font(label.getFont().getName(), Font.PLAIN, 90));
            model_points.addElement(label);
            
            if(buzzed_address > 0 && teampanels.get(i).team.getAddress() == buzzed_address){               
                selected_index = i;              
            }
        }
        
        jList_Teams.setModel(model_teams);
        jList_Points.setModel(model_points);
        
        if(selected_index >= 0){               
            jList_Teams.setSelectedIndex(selected_index);
            jList_Points.setSelectedIndex(selected_index);               
        }
        
        
    }
    
    //select team on list
    public void selectTeam(int address){
        for(int i = 0; i<teampanels.size(); i++){
            if(teampanels.get(i).team.getAddress() == address){
                jList_Teams.setSelectedIndex(i);
                jList_Points.setSelectedIndex(i);
                buzzed_address = address;
                break;
            }
        }
        
    }
    
    //unselect list
    public void unselectTeam(){
        jList_Teams.clearSelection();
        jList_Points.clearSelection();
        buzzed_address = -1;
    }
    
    //listrenderer used to display jLabel components in the list
    private class LabelRenderer implements ListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            JLabel renderer = (JLabel) value;
            
            //select
            if(isSelected){
                renderer.setBackground(renderer.getForeground().darker().darker());
                renderer.setOpaque(true);
            }
            else{
                renderer.setOpaque(false);
            }
            return renderer;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList_Points;
    private javax.swing.JList<String> jList_Teams;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
